# ==============================================================
#           VOLLEYBALL GROUP ACTIVITY RECOGNITION CONFIG
# ==============================================================

dataset:
  root: "/mnt/d/Desktop/04 Project/volleyball-datasets"

  crops_annots_path: "/mnt/d/Desktop/04 Project/volleyball-datasets/volleyball_tracking_annotation/volleyball_tracking_annotation"
  frames_annots_path: "/mnt/d/Desktop/04 Project/volleyball-datasets/volleyball_/videos"

output:
  save_dir: "./processed_data"


